logging:
    level:
        root: INFO
server:
    port: 9091
    servlet:
        context-path: /BOOK-STORE
spring:
    datasource:
        password: 
        url: jdbc:mysql://localhost:3306/bookstore?useSSL=false
        username: root
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER